### ISSUE TITLE
txt2params.py not installed by "make install"

### ISSUE THREAD

**Issue by cgleggett** [ROCm/rocprofiler#30]
after a clean install, running rocprof results in:
```
Traceback (most recent call last):
  File "/opt/rocm-3.5.1/rocprofiler/bin/tblextr.py", line 26, in <module>
    from sqlitedb import SQLiteDB
  File "/opt/rocm-3.5.1/rocprofiler/bin/sqlitedb.py", line 3, in <module>
    from txt2params import gen_params
ImportError: No module named txt2params
```

looking at what's installed:
```
-- Installing: /opt/rocm-3.5.1/rocprofiler/bin/rpl_run.sh
-- Installing: /opt/rocm-3.5.1/rocprofiler/bin/txt2xml.sh
-- Installing: /opt/rocm-3.5.1/rocprofiler/bin/tblextr.py
-- Installing: /opt/rocm-3.5.1/rocprofiler/bin/dform.py
-- Installing: /opt/rocm-3.5.1/rocprofiler/bin/sqlitedb.py
```

```
> ls /opt/rocm-3.5.1/rocprofiler/bin
dform.py  rpl_run.sh  sqlitedb.py  tblextr.py  txt2xml.sh
```

**Comment by eshcherb** [comment]
Could you try roc-3.5 branch

**Comment by cgleggett** [comment]
roc-3.5 branch fixes this.

thanks.
