### ISSUE TITLE
tblextr.py: missing import of commands

### ISSUE THREAD

**Issue by cgleggett** [ROCm/rocprofiler#31]
running rocprofiler:
```
Traceback (most recent call last):
  File "/opt/rocm-3.5.1/rocprofiler/bin/tblextr.py", line 466, in <module>
    metadata_gen(sysinfo_file, '/opt/rocm/bin/rocminfo')
  File "/opt/rocm-3.5.1/rocprofiler/bin/tblextr.py", line 69, in metadata_gen
    status, output = commands.getstatusoutput(sysinfo_cmd + direct_str + sysinfo_file)
NameError: global name 'commands' is not defined
```

`import commands` needs to be added to `metadata_gen` function in tblextr.py

**Comment by eshcherb** [comment]
What branch are you using?
Could you try roc-3.5 branch?

**Comment by cgleggett** [comment]
I'm using amd-master.

I get a cmake error when using the roc-3.5 branch:
```
> cmake -DCMAKE_INSTALL_PREFIX=/opt/rocm-3.5.1 ../rocprofiler
----------------NBit: 64
----------Build-Type: release
------------Compiler: /opt/rh/devtoolset-7/root/bin/g++
----Compiler-Version: 7.3.1
-----HSA-Runtime-Inc: /opt/rocm/include/hsa
-----HSA-Runtime-Lib: /opt/rocm/lib
----HSA_KMT_LIB_PATH: /opt/rocm/lib64
-------ROCM_ROOT_DIR: /opt/rocm
-----CMAKE_CXX_FLAGS: -std=c++11 -Wall -Werror -Werror=return-type -fexceptions -fvisibility=hidden -fno-math-errno -fno-threadsafe-statics -fmerge-all-constants -fms-extensions -fmerge-all-constants -Werror=unused-result -fPIC -m64  -msse -msse2
---CMAKE_PREFIX_PATH: /opt/rocm/include/hsa:/opt/rocm
---------GPU_TARGETS: 
-- LIB-VERSION: 1.0.0
-- LIB-VERSION STRING: 1.0.0
CMake Error at CMakeLists.txt:90 (MESSAGE):
  Profiling API header not found.  Tracer integration disabled.  Use
  -DPROF_API_HEADER_PATH=<path to prof_protocol.h header>
```

**Comment by eshcherb** [comment]
Something strange. If you check roc-3.5 branch you will see that 'metagen_gen' function uses 'subprocess' python module:
https://github.com/ROCm-Developer-Tools/rocprofiler/blob/roc-3.5/bin/tblextr.py#L76

I will check with packaging team what was pacckaged in 3..5.1.

**Comment by cgleggett** [comment]
I had to add  `/opt/rocm/roctracer` to the `CMAKE_PREFIX_PATH` to get it to work.

Do I need to use the roc-3.5 branch of roctracer as well?

**Comment by eshcherb** [comment]
Do you have roctracer installed?
You can use the cmake parameter -DPROF_API_HEADER_PATH :
 -DPROF_API_HEADER_PATH=/opt/rocm/roctracer/icnlude/ext

**Comment by eshcherb** [comment]
Yes, please use roc-3.5 branch of roctracer as well.

**Comment by cgleggett** [comment]
there's a non-fatal error in the cmake step of roctracer:
```
+ /opt/rocm/llvm/bin/clang -cl-std=CL2.0 -include /opt/rocm/llvm/lib/clang/11.0.0/include/opencl-c.h -Xclang -mlink-bitcode-file -Xclang /opt/rocm/lib/bitcode/opencl.amdgcn.bc -Xclang -mlink-bitcode-file -Xclang /opt/rocm/lib/bitcode/ockl.amdgcn.bc -Xclang -mlink-bitcode-file -Xclang /opt/rocm/lib/bitcode/ocml.amdgcn.bc -target amdgcn-amd-amdhsa -mcpu=gfx900 -mno-code-object-v3 /home/leggett/install/roctracer/roctracer/test/hsa/test/dummy_kernel/dummy_kernel.cl -o /home/leggett/install/roctracer/bld/gfx900_DummyKernel.hsaco
fatal error: cannot open file '/opt/rocm/lib/bitcode/opencl.amdgcn.bc': No such file or directory
1 error generated.
```

`opencl.amdgcn.bc` is installed in `/opt/rocm/lib`. made a symlink, and it proceeded to completion.

**Comment by cgleggett** [comment]
using the rocm-3.5 branch fixed this issue.
